"use client";

/**
 * Gym member add/edit form (Phase 3.1).
 *
 * Create and edit share this component. Member codes are generated by the
 * database (unique per organization) and are immutable, so they are never part
 * of the form. Assigned trainer is display-only; writes go through trainer
 * assignment RPCs, not this form.
 */

import * as React from "react";
import { useRouter } from "next/navigation";
import { z } from "zod";
import { UserPlus, Users } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Button, ButtonLink } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FormField } from "@/components/ui/form-field";
import { FormSection } from "@/components/ui/form-section";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { EmptyState } from "@/components/ui/empty-state";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Modal } from "@/components/ui/modal";
import { AddressFields } from "@/components/onboarding/fields";
import { useOrganization } from "@/components/auth/org-provider";
import { useToast } from "@/components/ui/toast";
import {
  createGymMember,
  fetchGymMember,
  updateGymMember,
  type GymMemberWriteInput,
} from "@/lib/org/gym-members";
import {
  GYM_MEMBER_GENDERS,
  gymMemberFormSchema,
} from "@/lib/validation/auth-schemas";

type MemberValues = z.infer<typeof gymMemberFormSchema>;

function emptyValues(): MemberValues {
  return {
    firstName: "",
    lastName: "",
    phone: "",
    email: "",
    gender: "",
    dateOfBirth: "",
    branchId: "",
    joinedAt: "",
    emergencyContactName: "",
    emergencyContactPhone: "",
    notes: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    state: "",
    postalCode: "",
    country: "",
  };
}

function toValues(member: {
  firstName: string;
  lastName: string;
  phone: string;
  email: string | null;
  gender: string | null;
  dateOfBirth: string | null;
  branchId: string;
  joinedAt: string;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  notes: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  country: string | null;
}): MemberValues {
  return {
    firstName: member.firstName,
    lastName: member.lastName,
    phone: member.phone,
    email: member.email ?? "",
    gender: (member.gender ?? "") as MemberValues["gender"],
    dateOfBirth: member.dateOfBirth ? member.dateOfBirth.slice(0, 10) : "",
    branchId: member.branchId,
    joinedAt: member.joinedAt ? member.joinedAt.slice(0, 10) : "",
    emergencyContactName: member.emergencyContactName ?? "",
    emergencyContactPhone: member.emergencyContactPhone ?? "",
    notes: member.notes ?? "",
    addressLine1: member.addressLine1 ?? "",
    addressLine2: member.addressLine2 ?? "",
    city: member.city ?? "",
    state: member.state ?? "",
    postalCode: member.postalCode ?? "",
    country: member.country ?? "",
  };
}

export interface MemberFormProps {
  mode: "create" | "edit";
  memberId?: string;
}

export function MemberForm({ mode, memberId }: MemberFormProps) {
  const router = useRouter();
  const { toast } = useToast();
  const { organization, branches, currentBranchId, can } = useOrganization();
  const orgId = organization?.id;

  const canSubmit = mode === "create" ? can("members.create") : can("members.update");
  const canAssignMembership = can("memberships.create");
  const canAssignTrainer = can("trainers.assign");

  const [values, setValues] = React.useState<MemberValues>(emptyValues);
  const [initialValues, setInitialValues] = React.useState<MemberValues>(emptyValues);
  const [errors, setErrors] = React.useState<Partial<Record<keyof MemberValues, string>>>({});
  const [loading, setLoading] = React.useState(mode === "edit");
  const [loadError, setLoadError] = React.useState<string | null>(null);
  const [submitting, setSubmitting] = React.useState(false);
  const [trainerName, setTrainerName] = React.useState<string | null>(null);
  const [savedMemberId, setSavedMemberId] = React.useState<string | null>(null);
  const [leaveOpen, setLeaveOpen] = React.useState(false);

  // Default the branch to the current branch (create) or the member's branch.
  React.useEffect(() => {
    if (mode !== "create" || !branches.length) return;
    setValues((prev) => {
      if (prev.branchId) return prev;
      const next = { ...prev, branchId: currentBranchId ?? branches[0].id };
      setInitialValues(next);
      return next;
    });
  }, [mode, branches, currentBranchId]);

  React.useEffect(() => {
    if (mode !== "edit" || !orgId || !memberId) return;
    let cancelled = false;
    setLoading(true);
    void fetchGymMember(orgId, memberId).then((result) => {
      if (cancelled) return;
      setLoading(false);
      if (result.error) {
        setLoadError(result.error.message);
        return;
      }
      const next = toValues(result.data);
      setValues(next);
      setInitialValues(next);
      setTrainerName(result.data.assignedTrainerName);
    });
    return () => {
      cancelled = true;
    };
  }, [mode, orgId, memberId]);

  const setField = (field: string, value: string) => {
    setValues((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => (field in prev ? { ...prev, [field]: undefined } : prev));
  };

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (submitting || !orgId || !canSubmit) return;

    const parsed = gymMemberFormSchema.safeParse(values);
    if (!parsed.success) {
      const nextErrors: Partial<Record<keyof MemberValues, string>> = {};
      for (const issue of parsed.error.issues) {
        const key = issue.path[0] as keyof MemberValues | undefined;
        if (key && !nextErrors[key]) nextErrors[key] = issue.message;
      }
      setErrors(nextErrors);
      return;
    }

    setSubmitting(true);
    const input: GymMemberWriteInput = {
      organizationId: orgId,
      branchId: parsed.data.branchId,
      firstName: parsed.data.firstName,
      lastName: parsed.data.lastName,
      phone: parsed.data.phone,
      email: parsed.data.email || null,
      gender: parsed.data.gender || null,
      dateOfBirth: parsed.data.dateOfBirth || null,
      emergencyContactName: parsed.data.emergencyContactName || null,
      emergencyContactPhone: parsed.data.emergencyContactPhone || null,
      notes: parsed.data.notes || null,
      addressLine1: parsed.data.addressLine1 || null,
      addressLine2: parsed.data.addressLine2 || null,
      city: parsed.data.city || null,
      state: parsed.data.state || null,
      postalCode: parsed.data.postalCode || null,
      country: parsed.data.country || null,
      joinedAt: parsed.data.joinedAt || null,
    };

    const result =
      mode === "create"
        ? await createGymMember(input)
        : await updateGymMember(memberId as string, input);
    setSubmitting(false);

    if (result.error) {
      toast({
        title: mode === "create" ? "Could not add member" : "Could not save changes",
        description: result.error.message,
        variant: "error",
      });
      return;
    }

    toast({
      title: mode === "create" ? "Member added" : "Member updated",
      variant: "success",
    });
    const id = mode === "create" ? (result.data as { id: string }).id : memberId;
    setInitialValues(values);
    if (id) setSavedMemberId(id);
    router.refresh();
  };

  const isDirty = React.useMemo(
    () => JSON.stringify(values) !== JSON.stringify(initialValues),
    [values, initialValues],
  );

  React.useEffect(() => {
    if (!isDirty) return;
    const onBeforeUnload = (event: BeforeUnloadEvent) => {
      event.preventDefault();
      event.returnValue = "";
    };
    window.addEventListener("beforeunload", onBeforeUnload);
    return () => window.removeEventListener("beforeunload", onBeforeUnload);
  }, [isDirty]);

  const requestLeave = () => {
    if (isDirty && !savedMemberId) {
      setLeaveOpen(true);
      return;
    }
    router.push("/members");
  };

  const branchOptions = branches.map((branch) => ({
    value: branch.id,
    label: `${branch.name} (${branch.code})`,
  }));

  if (mode === "edit" && loading) {
    return (
      <div className="space-y-6">
        <PageHeader title="Edit member" icon={Users} />
        <LoadingState label="Loading member…" />
      </div>
    );
  }

  if (mode === "edit" && loadError) {
    return (
      <div className="space-y-6">
        <PageHeader title="Edit member" icon={Users} />
        <ErrorState
          description={loadError}
          onRetry={() => router.refresh()}
        />
      </div>
    );
  }

  if (!orgId) {
    return (
      <div className="space-y-6">
        <PageHeader title={mode === "create" ? "Add member" : "Edit member"} icon={Users} />
        <EmptyState
          title="Organization unavailable"
          description="Sign in with an organization to manage members."
          action={{ label: "Go to Dashboard", href: "/dashboard" }}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title={mode === "create" ? "Add member" : "Edit member"}
        description={
          mode === "create"
            ? "Register a new gym member. The member code is generated automatically."
            : `${values.firstName} ${values.lastName}`.trim()
        }
        icon={mode === "create" ? UserPlus : Users}
        actions={
          <Button type="button" variant="outline" onClick={requestLeave}>
            Back to members
          </Button>
        }
      />

      {!canSubmit && (
        <div className="rounded-card border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          You do not have permission to {mode === "create" ? "add" : "edit"} members.
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6" noValidate>
        <FormSection title="Personal details" description="Basic identity information.">
          <FormField label="First name" required error={errors.firstName}>
            <Input
              autoComplete="given-name"
              value={values.firstName}
              invalid={Boolean(errors.firstName)}
              onChange={(event) => setField("firstName", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Last name" required error={errors.lastName}>
            <Input
              autoComplete="family-name"
              value={values.lastName}
              invalid={Boolean(errors.lastName)}
              onChange={(event) => setField("lastName", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Date of birth" error={errors.dateOfBirth}>
            <Input
              type="date"
              value={values.dateOfBirth ?? ""}
              invalid={Boolean(errors.dateOfBirth)}
              onChange={(event) => setField("dateOfBirth", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Gender" error={errors.gender}>
            <Select
              options={[...GYM_MEMBER_GENDERS]}
              value={values.gender}
              invalid={Boolean(errors.gender)}
              onChange={(event) => setField("gender", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
        </FormSection>

        <FormSection title="Contact" description="How to reach this member.">
          <FormField label="Phone" required error={errors.phone}>
            <Input
              type="tel"
              autoComplete="tel"
              placeholder="+91 90000 00000"
              value={values.phone}
              invalid={Boolean(errors.phone)}
              onChange={(event) => setField("phone", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Email" error={errors.email}>
            <Input
              type="email"
              autoComplete="email"
              placeholder="member@example.com"
              value={values.email ?? ""}
              invalid={Boolean(errors.email)}
              onChange={(event) => setField("email", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Emergency contact name" error={errors.emergencyContactName}>
            <Input
              value={values.emergencyContactName ?? ""}
              invalid={Boolean(errors.emergencyContactName)}
              onChange={(event) => setField("emergencyContactName", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField label="Emergency contact phone" error={errors.emergencyContactPhone}>
            <Input
              type="tel"
              value={values.emergencyContactPhone ?? ""}
              invalid={Boolean(errors.emergencyContactPhone)}
              onChange={(event) => setField("emergencyContactPhone", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
        </FormSection>

        <FormSection title="Membership" description="Branch and join date for this member.">
          <FormField label="Branch" required error={errors.branchId}>
            <Select
              options={branchOptions}
              placeholder="Select a branch"
              value={values.branchId}
              invalid={Boolean(errors.branchId)}
              onChange={(event) => setField("branchId", event.target.value)}
              disabled={!canSubmit || branches.length === 0}
            />
          </FormField>
          <FormField label="Join date" error={errors.joinedAt} hint="Defaults to today when left empty.">
            <Input
              type="date"
              value={values.joinedAt ?? ""}
              invalid={Boolean(errors.joinedAt)}
              onChange={(event) => setField("joinedAt", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
          <FormField
            label="Assigned trainer"
            hint="Trainer assignment is managed from Trainers, not this form."
          >
            <div className="flex flex-wrap items-center gap-3 pt-1">
              {trainerName ? (
                <Badge tone="primary">{trainerName}</Badge>
              ) : (
                <Badge tone="neutral">Unassigned</Badge>
              )}
              {canAssignTrainer && memberId && (
                <ButtonLink
                  href={`/trainers/assignments/add?memberId=${memberId}`}
                  variant="outline"
                  size="sm"
                >
                  {trainerName ? "Change trainer" : "Assign trainer"}
                </ButtonLink>
              )}
            </div>
          </FormField>
        </FormSection>

        <FormSection title="Address" description="Optional address details." columns={1}>
          <AddressFields
            values={values as unknown as Record<string, string>}
            errors={errors as unknown as Record<string, string | undefined>}
            onChange={setField}
            disabled={!canSubmit}
          />
        </FormSection>

        <FormSection title="Notes" description="Internal notes about this member." columns={1}>
          <FormField label="Notes" error={errors.notes}>
            <Textarea
              rows={3}
              value={values.notes ?? ""}
              invalid={Boolean(errors.notes)}
              onChange={(event) => setField("notes", event.target.value)}
              disabled={!canSubmit}
            />
          </FormField>
        </FormSection>

        <div className="flex flex-wrap items-center justify-end gap-3">
          <Button type="button" variant="outline" onClick={requestLeave}>
            Cancel
          </Button>
          <Button type="submit" isLoading={submitting} disabled={!canSubmit}>
            {mode === "create" ? "Add member" : "Save changes"}
          </Button>
        </div>
      </form>

      <ConfirmDialog
        open={leaveOpen}
        onClose={() => setLeaveOpen(false)}
        onConfirm={() => {
          setLeaveOpen(false);
          router.push("/members");
        }}
        title="Discard unsaved changes?"
        description="Your edits will be lost if you leave this page."
        confirmLabel="Discard"
        tone="danger"
      />

      <Modal
        open={savedMemberId !== null}
        onClose={() => {
          if (savedMemberId) router.push(`/members/${savedMemberId}`);
        }}
        title={mode === "create" ? "Member added" : "Member updated"}
        description="Choose the next step for this member."
        footer={
          <>
            <Button
              variant="outline"
              onClick={() => savedMemberId && router.push(`/members/${savedMemberId}`)}
            >
              View member
            </Button>
            {canAssignMembership && savedMemberId && (
              <Button
                onClick={() =>
                  router.push(`/memberships/active/add?memberId=${savedMemberId}`)
                }
              >
                Add membership
              </Button>
            )}
          </>
        }
      >
        <p className="text-sm text-neutral-600">
          {canAssignMembership
            ? "You can open the profile now or assign a membership plan."
            : "Open the member profile to continue."}
        </p>
      </Modal>
    </div>
  );
}
